const data = {
    countries: [
        {
            slug: 'nick-johnes',
            country: 'Australia',
            code: 'AU',
            quantity: 6,
            title: 'Dikins & Jones',
            distance: 2.43,
            street: '80 George Street, Richmond,tw9 1HA',
            phone: 180252663,
            status: 'closed',
            work: 'Opens At 6:00pm',
        },
        {
            slug: 'ikins-jones',
            country: 'Australia',
            code: 'AU',
            title: 'Richmond & Jones',
            distance: 4.53,
            street: '80 George Street, Richmond,tw9 1HA',
            phone: 130242663,
            status: 'closed',
            work: 'Opens At 4:00pm',
        },
        {
            slug: 'kins-jones',
            country: 'Australia',
            code: 'AU',
            title: 'Dikins & Jones',
            distance: 2.43,
            street: '80 George Street, Richmond,tw9 1HA',
            phone: 180252663,
            status: 'closed',
            work: 'Opens At 6:00pm',
        },
        {
            slug: 'dikiin-johnes',
            country: 'Australia',
            code: 'AU',
            amount: 6,
            title: 'Dikins & Jones',
            distance: 8.33,
            street: '80 George Street, Richmond,tw9 1HA',
            phone: 180252663,
            status: 'closed',
            work: 'Opens At 7:00pm',
        },
        {
            slug: 'dvikin-johnes',
            country: 'Australia',
            code: 'AU',
            amount: 6,
            title: 'Dikns & Jones',
            distance: 2.43,
            street: '90 George Street, Richmond,tw9 1HA',
            phone: 180252663,
            status: 'closed',
            work: 'Opens At 6:00pm',
        },
        {
            slug: 'dikiyn-johnes',
            country: 'Australia',
            code: 'AU',
            amount: 6,
            title: 'Dikins & Jones',
            distance: 12.42,
            street: '10 George Street, Richmond,tw9 1HA',
            phone: 480252633,
            status: 'closed',
            work: 'Opens At 6:00pm',
        },
        {
            slug: 'dyern-johnes',
            country: 'Australia',
            code: 'AU',
            title: 'Dikins & Jones',
            distance: 2.43,
            street: '80 George Street, Richmond,tw9 1HA',
            phone: 180252663,
            status: 'closed',
            work: 'Opens At 6:00pm',
        },
        {
            slug: 'pikin-johnes',
            country: 'Austria',
            code: 'AT',
            amount: 2,
            title: 'Dikins & Jones',
            distance: 3.83,
            street: '80 George Street, Richmond,tw9 1HA',
            phone: 180252663,
            status: 'closed',
            work: 'Opens At 6:00pm',
        },
        {
            slug: 'pkin-johnes',
            country: 'Austria',
            code: 'AT',
            amount: 2,
            title: 'Dikins & Jones',
            distance: 8.88,
            street: '80 George Street, Richmond,tw9 1HA',
            phone: 180252663,
            status: 'closed',
            work: 'Opens At 6:00pm',
        },
        {
            slug: 'eikwn-johnes',
            country: 'Brazil',
            code: 'BR',
            amount: 2,
            title: 'Dikins & Jones',
            distance: 3.83,
            street: '80 George Street, Richmond,tw9 1HA',
            phone: 180252663,
            status: 'closed',
            work: 'Opens At 7:00pm',
        },
        {
            slug: 'eikwcn-johnes',
            country: 'Brazil',
            code: 'BR',
            amount: 2,
            title: 'Dikins & Jones',
            distance: 11.83,
            street: '30 George Street, Richmond,tw9 1HA',
            phone: 180252663,
            status: 'closed',
            work: 'Opens At 7:00pm',
        },        
        {
            slug: 'eikwn-johnes',
            country: 'Canada',
            code: 'CA',
            amount: 1,
            title: 'Dikins & Jones',
            distance: 112.84,
            street: '80 George Street, Richmond,tw9 1HA',
            phone: 180252663,
            status: 'closed',
            work: 'Opens At 7:00pm',
        },       
        {
            slug: 'eiqkwn-johnes',
            country: 'China',
            code: 'CN',
            amount: 3,
            title: 'Dikins & Jones',
            distance: 122.24,
            street: '80 George Street, Richmond,tw9 1HA',
            phone: 180252663,
            status: 'closed',
            work: 'Opens At 6:00pm',
        }, 
        {
            slug: 'eiqkan-johnes',
            country: 'China',
            code: 'CN',
            amount: 3,
            title: 'Dikins & Jones',
            distance: 18.294,
            street: '80 George Street, Richmond,tw9 1HA',
            phone: 180252663,
            status: 'closed',
            work: 'Opens At 6:00pm',
        },
        {
            slug: 'eicknn-johnes',
            country: 'China',
            code: 'CN',
            amount: 3,
            title: 'Dikins & Jones',
            distance: 82.24,
            street: '80 George Street, Richmond,tw9 1HA',
            phone: 180252663,
            status: 'closed',
            work: 'Opens At 6:00pm',
        },             
        {
            slug: 'eiqkno-johnes',
            country: 'Germany',
            code: 'DE',
            amount: 2,
            title: 'Dikins & Jones',
            distance: 62.23,
            street: '80 George Street, Richmond,tw9 1HA',
            phone: 180252663,
            status: 'closed',
            work: 'Opens At 6:00pm',
        },
        {
            slug: 'eixqkno-johnes',
            country: 'Germany',
            code: 'DE',
            amount: 2,
            title: 'Dikins & Jones',
            distance: 72.28,
            street: '80 George Street, Richmond,tw9 1HA',
            phone: 120552663,
            status: 'closed',
            work: 'Opens At 6:00pm',
        },           
        {
            slug: 'eiqgno-johnes',
            country: 'Ghana',
            code: 'GH',
            amount: 1,
            title: 'Dikins & Jones',
            distance: 622.23,
            street: '80 George Street, Richmond,tw9 1HA',
            phone: 180252663,
            status: 'closed',
            work: 'Opens At 4:00pm',
        },         
        {
            slug: 'fiqcno-johnes',
            country: 'France',
            code: 'FR',
            amount: 3,
            title: 'Dikins & Jones',
            distance: 54.23,
            street: '80 George Street, Richmond,tw9 1HA',
            phone: 180252663,
            status: 'closed',
            work: 'Opens At 5:00pm',
        },
        {
            slug: 'etiqkno-johnes',
            country: 'France',
            code: 'FR',
            amount: 3,
            title: 'Dikins & Jones',
            distance: 22.29,
            street: '80 George Street, Richmond,tw9 1HA',
            phone: 180252663,
            status: 'closed',
            work: 'Opens At 4:00pm',
        }, 
        {
            slug: 'erqkno-jhnes',
            country: 'France',
            code: 'FR',
            amount: 3,
            title: 'Dikins & Jones',
            distance:232.26,
            street: '80 George Street, Richmond,tw9 1HA',
            phone: 180252663,
            status: 'closed',
            work: 'Opens At 5:00pm',
        },         
        {
            slug: 'etiqbno-johnes',
            country: 'Hong Kong',
            code: 'HK',
            amount: 2,
            title: 'Dikins & Jones',
            distance: 32.27,
            street: '80 George Street, Richmond,tw9 1HA',
            phone: 180252663,
            status: 'closed',
            work: 'Opens At 4:00pm',
        }, 
        {
            slug: 'etiqbno-jounes',
            country: 'Hong Kong',
            code: 'HK',
            amount: 2,
            title: 'Dikins & Jones',
            distance: 32.27,
            street: '80 George Street, Richmond,tw9 1HA',
            phone: 180252663,
            status: 'closed',
            work: 'Opens At 4:00pm',
        }, 
        {
            slug: 'erbeno-johnes',
            country: 'India',
            code: 'IN',
            amount: 1,
            title: 'Dikins & Jones',
            distance: 342.27,
            street: '80 George Street, Richmond,tw9 1HA',
            phone: 180252663,
            status: 'closed',
            work: 'Opens At 4:00pm',
        }, 
        {
            slug: 'etiteno-johnes',
            country: 'Irenland',
            code: 'IE',
            amount: 1,
            title: 'Dikins & Jones',
            distance: 65.22,
            street: '80 George Street, Richmond,tw9 1HA',
            phone: 180252663,
            status: 'closed',
            work: 'Opens At 4:00pm',
        }, 
        {
            slug: 'ekiqbnlo-johnes',
            country: 'Korea',
            code: 'KR',
            amount: 2,
            title: 'Dikins & Jones',
            distance: 82.23,
            street: '80 George Street, Richmond,tw9 1HA',
            phone: 180252663,
            status: 'closed',
            work: 'Opens At 6:00pm',
        }, 
        {
            slug: 'ekiqbclo-johnes',
            country: 'Korea',
            code: 'KR',
            amount: 2,
            title: 'Dikins & Jones',
            distance: 92.43,
            street: '80 George Street, Richmond,tw9 1HA',
            phone: 180252663,
            status: 'closed',
            work: 'Opens At 6:00pm',
        }, 
        {
            slug: 'aviqbnlo-johnes',
            country: 'Saudi Arabia',
            code: 'SA',
            amount: 3,
            title: 'Dikins & Jones',
            distance: 82.23,
            street: '80 George Street, Richmond,tw9 1HA',
            phone: 180252663,
            status: 'closed',
            work: 'Opens At 6:00pm',
        }, 
        {
            slug: 'avitelo-johnes',
            country: 'Saudi Arabia',
            code: 'SA',
            amount: 3,
            title: 'Dikins & Jones',
            distance: 9.23,
            street: '80 George Street, Richmond,tw9 1HA',
            phone: 180252663,
            status: 'closed',
            work: 'Opens At 5:00pm',
        }, 
        {
            slug: 'avdqbnlo-jbcnes',
            country: 'Saudi Arabia',
            code: 'SA',
            amount: 3,
            title: 'Dikins & Jones',
            distance: 12.23,
            street: '80 George Street, Richmond,tw9 1HA',
            phone: 180252663,
            status: 'closed',
            work: 'Opens At 6:00pm',
        }, 
        {
            slug: 'siiqbnlo-johnes',
            country: 'Singapore',
            code: 'SG',
            amount: 1,
            title: 'Dikins & Jones',
            distance: 7.53,
            street: '80 George Street, Richmond,tw9 1HA',
            phone: 180252663,
            status: 'closed',
            work: 'Opens At 6:00pm',
        }, 
        {
            slug: 'avrto-johnes',
            country: 'Turkey',
            code: 'TR',
            amount: 2,
            title: 'Dikins & Jones',
            distance: 82.23,
            street: '80 George Street, Richmond,tw9 1HA',
            phone: 180252663,
            status: 'closed',
            work: 'Opens At 6:00pm',
        }, 
        {
            slug: 'avwsto-jobnes',
            country: 'Turkey',
            code: 'TR',
            amount: 2,
            title: 'Dikins & Jones',
            distance: 78.20,
            street: '80 George Street, Richmond,tw9 1HA',
            phone: 180252663,
            status: 'closed',
            work: 'Opens At 6:00pm',
        }, 
        {
            slug: 'ubrto-johnes',
            country: 'United States',
            code: 'US',
            amount: 4,
            title: 'Dikins & Jones',
            distance: 112.23,
            street: '80 George Street, Richmond,tw9 1HA',
            phone: 180252663,
            status: 'closed',
            work: 'Opens At 6:00pm',
        }, 
        {
            slug: 'uorto-johnms',
            country: 'United States',
            code: 'US',
            amount: 4,
            title: 'Dikins & Jones',
            distance: 172.24,
            street: '80 George Street, Richmond,tw9 1HA',
            phone: 180252663,
            status: 'closed',
            work: 'Opens At 6:00pm',
        }, 
        {
            slug: 'ubbio-jophnes',
            country: 'United States',
            code: 'US',
            amount: 4,
            title: 'Dikins & Jones',
            distance: 112.23,
            street: '10 George Street, Richmond,tw9 1HA',
            phone: 180252663,
            status: 'closed',
            work: 'Opens At 6:00pm',
        }, 
        {
            slug: 'ubbso-johes',
            country: 'United States',
            code: 'US',
            amount: 4,
            title: 'Dikins & Jones',
            distance: 107.25,
            street: '80 George Street, Richmond,tw9 1HA',
            phone: 180252663,
            status: 'closed',
            work: 'Opens At 6:00pm',
        },        
    ],
}

export default data;